# Generated by Django 5.2.1 on 2025-07-10 14:47

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.save_avatar_to, verbose_name='аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активированный аккаунт'),
        ),
    ]
